- hosts: webservers
  tasks:
  - name: "Install web server"  
    package:
      name: "httpd"
      state: present


  - name: "Copy contents to index file"
    copy: 
      dest: "/var/www/html/index.html"
      content: "This is the {{ ansible_facts['enp0s8']['ipv4']['address'] }}"
      
  - name: "Enabling load balancer firewall"
    ansible.posix.firewalld: 
      port: "80/tcp"
      state: enabled
      permanent: yes
      immediate: yes

  - name: "Restart httpd service"
    service:
      name: "httpd"
      state: restarted

- hosts: loadbalancer
  tasks:
  - name: "Install the loadbalancer"
    package:
      name: "haproxy"
      state: present


  - name: "disabling the selinux"
    ansible.posix.selinux:
      state: disabled

  - name: "Enabling load balancer firewall"
    ansible.posix.firewalld: 
      port: "8080/tcp"
      state: enabled
      permanent: yes
      immediate: yes

  - name: "Restart the load balancer"
    service:
      name: "haproxy"
      state: restarted
     
       
    