- hosts: all
  vars_prompt:
  - name: rhel_dvd_path
    private: yes
    prompt: "Please enter the mount point for DVD:"

  - name: document_root
    private: no
  tasks:
  - file:
      state: directory
      path: "{{ rhel_dvd_path }}"

  - mount:
      src: "/dev/sr1"
      path: "{{ rhel_dvd_path }}"
      state: mounted
      fstype: "iso9660"

  - yum_repository:
      baseurl: "{{ rhel_dvd_path }}/AppStream"
      name: "mydvd1"
      description: "myyumdvd1 for package"
      gpgcheck: no

  - yum_repository:
      baseurl: "{{ rhel_dvd_path }}/BaseOS"
      name: "mydvd2"
      description: "myyumdvd2 for package"
      gpgcheck: no

  - package: 
      name: "httpd"
      state: present

  - copy: 
      dest: "/etc/httpd/conf.d/httpd.conf"
      src: "httpd.conf"

  - file:
      state: directory
      path: "{{ document_root }}" 
  
  - copy:
      dest: "{{ document_root }}/index.html"
      content: "This is mysite on 14/02/2021"

  - service:
      name: "httpd"
      state: restarted
      enabled: yes

  - firewalld:
      port: "8080/tcp"
      state: enabled
      permanent: yes
      immediate: yes

  - debug:
      msg: "{{ rhel_dvd_path }} and {{ document_root }}"